#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=Stan Grishin <stangri@melmac.net>

LUCI_TITLE:=Material Theme (Old Style)
LUCI_DESCRIPTION:=This is Material Theme with the old style colorful buttons.
LUCI_DEPENDS:=
PKG_RELEASE:=2

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
