#!/bin/sh

uci -q batch <<-EOT
	delete firewall.pbr
	set firewall.pbr='include'
	set firewall.pbr.fw4_compatible='1'
	set firewall.pbr.type='script'
	set firewall.pbr.path='/usr/share/pbr/pbr.firewall.include'
	commit firewall
EOT

exit 0
