#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vpnbypass[-1]
	add ucitrack vpnbypass
	set ucitrack.@vpnbypass[-1].init=vpnbypass
	commit ucitrack
EOF

rm -rf /var/luci-modulecache/; rm -f /var/luci-indexcache;
exit 0

