#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@fakeinternet[-1]
	add ucitrack fakeinternet
	set ucitrack.@fakeinternet[-1].init=fakeinternet
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
