#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wlanblinker[-1]
	add ucitrack wlanblinker
	set ucitrack.@wlanblinker[-1].init=wlanblinker
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
